import type { Venue } from '../types/venue'

const quote = (value: string) => `'${value.replaceAll("'", "''")}'`

/**
 * SQL that loads the venue's seats into the `seats` table. Written to
 * `supabase/seed.sql` by `npm run db:seed`, so the map and the database share one
 * source of truth (`venueConfig`).
 */
export function buildSeedSql(venue: Venue): string {
  const rows = venue.seats.map(
    (s) => `  (${quote(s.id)}, ${quote(s.sectionId)}, ${s.row}, ${s.number}, ${quote(s.tierId)}, ${Math.round(s.price * 100)})`,
  )
  return [
    '-- Generated by `npm run db:seed` from src/venue/venueConfig.ts. Do not edit by hand.',
    'insert into public.seats (id, section, row, number, tier_id, price_cents) values',
    rows.join(',\n'),
    'on conflict (id) do update set',
    '  section = excluded.section,',
    '  row = excluded.row,',
    '  number = excluded.number,',
    '  tier_id = excluded.tier_id,',
    '  price_cents = excluded.price_cents;',
    '',
  ].join('\n')
}
